disabled_rules:
  - trailing_comma
  - identifier_name

opt_in_rules:
  - empty_count
  - closure_spacing

excluded:
  - .build

line_length:
  warning: 140
  error: 200

type_body_length:
  warning: 250
  error: 400

file_length:
  warning: 400
  error: 600
